In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [4]:
wine = pd.read_csv('./data/wine_data.csv', names = ["Cultivator", "Alchol", "Malic_Acid", "Ash", "Alcalinity_of_Ash", "Magnesium", "Total_phenols", "Falvanoids", "Nonflavanoid_phenols", "Proanthocyanins", "Color_intensity", "Hue", "OD280", "Proline"])
wine.head()

Cultivator  Alchol  Malic_Acid   Ash  Alcalinity_of_Ash  Magnesium  \
0           1   14.23        1.71  2.43               15.6        127   
1           1   13.20        1.78  2.14               11.2        100   
2           1   13.16        2.36  2.67               18.6        101   
3           1   14.37        1.95  2.50               16.8        113   
4           1   13.24        2.59  2.87               21.0        118   

   Total_phenols  Falvanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color_intensity   Hue  OD280  Proline  
0             5.64  1.04   3.92     1065  
1             4.38  1.05   3.40     1050  
2             5.68  1.03   3.17     1185  
3             7.80  0.86   3.45     1480  
4             4.32  1.04   2.93      735

In [5]:
wine.describe().transpose()

count        mean         std     min       25%  \
Cultivator            178.0    1.938202    0.775035    1.00    1.0000   
Alchol                178.0   13.000618    0.811827   11.03   12.3625   
Malic_Acid            178.0    2.336348    1.117146    0.74    1.6025   
Ash                   178.0    2.366517    0.274344    1.36    2.2100   
Alcalinity_of_Ash     178.0   19.494944    3.339564   10.60   17.2000   
Magnesium             178.0   99.741573   14.282484   70.00   88.0000   
Total_phenols         178.0    2.295112    0.625851    0.98    1.7425   
Falvanoids            178.0    2.029270    0.998859    0.34    1.2050   
Nonflavanoid_phenols  178.0    0.361854    0.124453    0.13    0.2700   
Proanthocyanins       178.0    1.590899    0.572359    0.41    1.2500   
Color_intensity       178.0    5.058090    2.318286    1.28    3.2200   
Hue                   178.0    0.957449    0.228572    0.48    0.7825   
OD280                 178.0    2.611685    0.709990    1.27    1.9375   
Proline               178.0  746.893258  314.907474  278.00  500.5000   

                          50%       75%      max  
Cultivator              2.000    3.0000     3.00  
Alchol                 13.050   13.6775    14.83  
Malic_Acid              1.865    3.0825     5.80  
Ash                     2.360    2.5575     3.23  
Alcalinity_of_Ash      19.500   21.5000    30.00  
Magnesium              98.000  107.0000   162.00  
Total_phenols           2.355    2.8000     3.88  
Falvanoids              2.135    2.8750     5.08  
Nonflavanoid_phenols    0.340    0.4375     0.66  
Proanthocyanins         1.555    1.9500     3.58  
Color_intensity         4.690    6.2000    13.00  
Hue                     0.965    1.1200     1.71  
OD280                   2.780    3.1700     4.00  
Proline               673.500  985.0000  1680.00

In [6]:
wine.shape

(178, 14)

In [7]:
X = wine.drop('Cultivator',axis=1)
y = wine['Cultivator']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [11]:
scaler = StandardScaler()

# Fit only to the training data
scaler.fit(X_train)

# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
mlp = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)
""" (hidden_layer_sizes=(100, ), activation=’relu’, solver=’adam’, alpha=0.0001, batch_size=’auto’, learning_rate=’constant’, learning_rate_init=0.001, power_t=0.5, max_iter=200, shuffle=True, random_state=None, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True, early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08, n_iter_no_change=10)

hidden_layer_sizes : tuple, length = n_layers - 2, default (100,)
    The ith element represents the number of neurons in the ith hidden layer.
    
activation : {‘identity’, ‘logistic’, ‘tanh’, ‘relu’}, default ‘relu’
    Activation function for the hidden layer.

        ‘identity’, no-op activation, useful to implement linear bottleneck, returns f(x) = x
        ‘logistic’, the logistic sigmoid function, returns f(x) = 1 / (1 + exp(-x)).
        ‘tanh’, the hyperbolic tan function, returns f(x) = tanh(x).
        ‘relu’, the rectified linear unit function, returns f(x) = max(0, x)

solver : {‘lbfgs’, ‘sgd’, ‘adam’}, default ‘adam’
    The solver for weight optimization.

        ‘lbfgs’ is an optimizer in the family of quasi-Newton methods.
        ‘sgd’ refers to stochastic gradient descent.
        ‘adam’ refers to a stochastic gradient-based optimizer proposed by Kingma, Diederik, and Jimmy Ba

    Note: The default solver ‘adam’ works pretty well on relatively large datasets (with thousands of training samples or
        more) in terms of both training time and validation score. For small datasets, however, ‘lbfgs’ can converge
        faster and perform better.
        
alpha : float, optional, default 0.0001
    L2 penalty (regularization term) parameter.
    
batch_size : int, optional, default ‘auto’
    Size of minibatches for stochastic optimizers. If the solver is ‘lbfgs’, the classifier will not use minibatch. When 
        set to “auto”, batch_size=min(200, n_samples)
        
learning_rate : {‘constant’, ‘invscaling’, ‘adaptive’}, default ‘constant’
    Learning rate schedule for weight updates.

        ‘constant’ is a constant learning rate given by ‘learning_rate_init’.
        ‘invscaling’ gradually decreases the learning rate learning_rate_ at each time step ‘t’ using an inverse scaling exponent of ‘power_t’. effective_learning_rate = learning_rate_init / pow(t, power_t)
        ‘adaptive’ keeps the learning rate constant to ‘learning_rate_init’ as long as training loss keeps decreasing. Each time two consecutive epochs fail to decrease training loss by at least tol, or fail to increase validation score by at least tol if ‘early_stopping’ is on, the current learning rate is divided by 5.

    Only used when solver='sgd'.
    
learning_rate_init : double, optional, default 0.001
    The initial learning rate used. It controls the step-size in updating the weights. Only used when solver=’sgd’ or 
        ‘adam’.
        
power_t : double, optional, default 0.5
    The exponent for inverse scaling learning rate. It is used in updating effective learning rate when the learning_rate
        is set to ‘invscaling’. Only used when solver=’sgd’.
        
max_iter : int, optional, default 200
    Maximum number of iterations. The solver iterates until convergence (determined by ‘tol’) or this number of iterations.
        For stochastic solvers (‘sgd’, ‘adam’), note that this determines the number of epochs (how many times each data point
        will be used), not the number of gradient steps.
        
shuffle : bool, optional, default True
    Whether to shuffle samples in each iteration. Only used when solver=’sgd’ or ‘adam’.
    
random_state : int, RandomState instance or None, optional, default None
    If int, random_state is the seed used by the random number generator; If RandomState instance, random_state is the
        random number generator; If None, the random number generator is the RandomState instance used by np.random.
        
tol : float, optional, default 1e-4
    Tolerance for the optimization. When the loss or score is not improving by at least tol for n_iter_no_change 
        consecutive iterations, unless learning_rate is set to ‘adaptive’, convergence is considered to be reached and 
        training stops.

verbose : bool, optional, default False
    Whether to print progress messages to stdout.
    
warm_start : bool, optional, default False
    When set to True, reuse the solution of the previous call to fit as initialization, otherwise, just erase the previous
        solution. See the Glossary.
        
momentum : float, default 0.9
    Momentum for gradient descent update. Should be between 0 and 1. Only used when solver=’sgd’.
    
nesterovs_momentum : boolean, default True
    Whether to use Nesterov’s momentum. Only used when solver=’sgd’ and momentum > 0.
    
early_stopping : bool, default False
    Whether to use early stopping to terminate training when validation score is not improving. If set to true, it will 
        automatically set aside 10% of training data as validation and terminate training when validation score is not 
        improving by at least tol for n_iter_no_change consecutive epochs. Only effective when solver=’sgd’ or ‘adam’
        
validation_fraction : float, optional, default 0.1
    The proportion of training data to set aside as validation set for early stopping. Must be between 0 and 1. Only used 
        if early_stopping is True
        
beta_1 : float, optional, default 0.9
    Exponential decay rate for estimates of first moment vector in adam, should be in [0, 1). Only used when solver=’adam’
    
beta_2 : float, optional, default 0.999
    Exponential decay rate for estimates of second moment vector in adam, should be in [0, 1). Only used when solver=’adam’
    
epsilon : float, optional, default 1e-8
    Value for numerical stability in adam. Only used when solver=’adam’
    
n_iter_no_change : int, optional, default 10
    Maximum number of epochs to not meet tol improvement. Only effective when solver=’sgd’ or ‘adam’

"""

In [13]:
mlp.fit(X_train,y_train)
predictions = mlp.predict(X_test)

In [17]:
print(predictions)

[3 2 1 1 2 2 2 1 3 1 3 1 3 2 3 2 1 2 1 2 1 3 1 2 2 3 1 2 3 2 2 2 2 3 3 2 2
 2 1 2 2 2 1 1 1]


In [19]:
print(confusion_matrix(y_test,predictions))
""" (y_true, y_pred, labels=None, sample_weight=None)

y_true : array, shape = [n_samples]
    Ground truth (correct) target values.
    
y_pred : array, shape = [n_samples]
    Estimated targets as returned by a classifier.
    
labels : array, shape = [n_classes], optional
    List of labels to index the matrix. This may be used to reorder or select a subset of labels. If none is given, those
        that appear at least once in y_true or y_pred are used in sorted order.
sample_weight : array-like of shape = [n_samples], optional
    Sample weights.

"""

[[13  0  0]
 [ 1 21  1]
 [ 0  0  9]]


In [20]:
print(classification_report(y_test,predictions))
""" (y_true, y_pred, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False)[source]

y_true : 1d array-like, or label indicator array / sparse matrix
    Ground truth (correct) target values.
    
y_pred : 1d array-like, or label indicator array / sparse matrix
    Estimated targets as returned by a classifier.
    
labels : array, shape = [n_labels]
    Optional list of label indices to include in the report.
    
target_names : list of strings
    Optional display names matching the labels (same order).
    
sample_weight : array-like of shape = [n_samples], optional
    Sample weights.
    
digits : int
    Number of digits for formatting output floating point values. When output_dict is True, this will be ignored and the
        returned values will not be rounded.
output_dict : bool (default = False)
    If True, return output as dict


"""

             precision    recall  f1-score   support

          1       0.93      1.00      0.96        13
          2       1.00      0.91      0.95        23
          3       0.90      1.00      0.95         9

avg / total       0.96      0.96      0.96        45

